### ISSUE TITLE
Segfault in memmove on 32-bit platform

### ISSUE THREAD

**Issue by bnavigator** [frejanordsiek/hdf5storage#109]
The tests reading Matlab files fail on 32-bit with a Segmentation fault in `memmove` called by `read_matlab_fields_attribute`

buildlog for 0.1.16 with nosetests: [hdf5storage_i586_log.txt](https://github.com/frejanordsiek/hdf5storage/files/6103421/hdf5storage_i586_log.txt)
gdb backtrace: [python-nosetest-gdb.log](https://github.com/frejanordsiek/hdf5storage/files/6103403/python-nosetest-gdb.log)

buildlog for master with pytest: [hdf5storage-master-log.txt](https://github.com/frejanordsiek/hdf5storage/files/6103579/hdf5storage-master-log.txt)
gdb backtrace: [hdf5storage-master-gdb.log](https://github.com/frejanordsiek/hdf5storage/files/6103580/hdf5storage-master-gdb.log)

**Comment by frejanordsiek** [comment]
Looks like my fix for #102 doesn't work for 32-bit systems. Was worried about this. Same for big-endian systems. I am going to try to get 32-bit python and HDF5 libraries going in a VM or a 32-bit VM to be able to find an improved workaround that will work on both 32-bit and 64-bit systems.

**Comment by frejanordsiek** [comment]
Fixed for 32-bit little endian systems in commit 9f021ee for the 0.1.x branch and commit c8a306e for the main branch. I still don't know if it works on big-endian systems.

**Comment by frejanordsiek** [comment]
Had a bug in the fix, which is now fixed in more recent commits.

**Comment by bnavigator** [comment]
The big endian (64-bit) build targets on the openSUSE build service pass build and pass the unit tests: https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/python-hdf5storage (0.1.x branch)
The i586 target passes locally as well. The obs scheduler didn't pick up yet that it has been reenabled online.

Any plans to make a 0.2 release soon?

**Comment by frejanordsiek** [comment]
Just uploaded version 0.1.17 to PyPI which includes the fix.

@bnavigator Good to know there are not problems on 64-bit big-endian systems. I'm still trying to get my own automated multi-architecture unit testing system going to catch these things, but it getting the automation working is going slowly. Hopefully, I will catch more of these kinds of errors in the future. Made some progress on 64-bit little endian systems (x86_64, aarch64, ppc64le); but need a lot more work to include 32-bit little endian (i686), 32-bit big-endian systems (armel and armhf), and 64-bit big endian. Since I need to include a 64-bit big endian, what kind of system are you using for openSUSE for this?

@bnavigator As for 0.2, I was planning on soon changing it to 1.0 and releasing it soon, but I hit a major roadblock in solving Issue #108 . I haven't yet figured out how to properly add support for circular objects. Unfortunately, whatever the solution will be, it will result in a massive non-backwards compatible change in the API. In principle, I could work towards a release that adds all the other things on the todo list (relatively quick to do) but not support circular objects, and then do circular objects later. But, this would be a high maintenance work load since that would eventually mean maintaining 3 separate branches for years. So, I am going to wait and work on it more and put it all into a single release. That will mean maintaining only 2 branches since each branch is a multi-year commitment (haven't decided how much longer the 0.1.x branch will be supported after the 1.0 release, but I am thinking of 3-5 years probably).

**Comment by bnavigator** [comment]
The open build service can be used [to build on your local workstation inside chroot or qemu virtual machines](https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.building.html), but the main feature is the server farm of build.opensuse.org which has a bunch of [x86_64 workers, ARM, PPC and S390](https://build.opensuse.org/monitor). Unfortunately, I don't see any 32-bit big endian architectures listed.

https://openbuildservice.org/

**Comment by frejanordsiek** [comment]
Thank you. That looks like it could be useful.

As far as 32-bit big endian, I could just run raspbian in qemu for arm. Probably good enough.
