### ISSUE TITLE
`structs_as_dicts` option does not work using `loadmat()`

### ISSUE THREAD

**Issue by gvnwst** [frejanordsiek/hdf5storage#115]
As my current understanding of the package goes, the `Options` object cannot be passed to `loadmat` (and it doesn't appear to be an object whose state is observed by the various loading functions?). 

## Example

I created a simple (v7.3) `.mat` file with a single variable `A`, which is a Matlab struct. It is defined like this:
```
A.one = zeros(3,3)
A.two = 'First level char'
A.three.nested = 'char in nested structure'
```

To load, I run
``` 
indata = hdf5storage.loadmat( file_name='simple_test.mat' )
```
which returns a dict containing a nested array:
```
indata['A'] = array([([[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]], [['first level char']], [([['char in nested struct']],)])],
      dtype=[('one', '<f8', (3, 3)), ('two', '<U16', (1, 1)), ('three', [('nested', '<U21', (1, 1))], (1,))])
```

(I tried just generically creating an `Options` object `hdf5storage.Options(structs_as_dicts=True)` to see if having a an existing options object would be recognized and used.)

At the beginning of the definition of `loadmat` is a line which creates an options object (`hdf5storage/hdf5storage/__init__.py` at line 2539). This appears to be hard-coded. Changing it to 
``` options = Options(marshaller_collection=marshaller_collection, structs_as_dicts=True)```
and re-building, I get the following output when loading my `.mat`:

```
indata['A'] =
{'one': array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 'three': {'nested': array([['char in nested struct']], dtype='<U21')},
 'two': array([['first level char']], dtype='<U16')}
```
Which is much better (though it's converting chars into arrays of strings).

Is there a way of passing a user-defined `Options` to `loadmat`, or somewhere else I can override the hard-coded one? 

### System details 

I cloned and installed `hdf5storage` v0.2 from source, running Python 3.7.9 and `h5py` 3.2.1.

**Comment by frejanordsiek** [comment]
At present, there is no way to pass the options to ``loadmat``. Though fundamentally, there is no reason an additional keyword argument for the purpose can be added, which is what I will do.

As for the chars becoming arrays of strings, that is done to exactly match how Matlab represents/sees strings (though the printer in Matlab hides this for 1x1) and stores them. In this package, there are a number of places where choices had to be made with regards to Matlab compatibility on whether it was better to represent things exactly as Matlab does or to make them semantically similar when printed. For strings, I went with trying to match the representation exactly.

**Comment by frejanordsiek** [comment]
``loadmat`` has had an ``options`` argument added to allow an ``Options`` to be passed (note, it overrides the ``marshaller_collection`` argument if it is passed) in commit b1f450f5f087fb31b4a4905e10a15e8aacfb8d3b

**Comment by gvnwst** [comment]
Out of curiosity, why the choice to make the Matlab representation be matched identically? As a relatively new Python user, I feelthe most natural thing from a programmatic perspective is for matlab `char` (or `string`) to map directly to a python `string` -- unless it is a matlab string array, which might become a python array of strings as it is now.

**Comment by frejanordsiek** [comment]
I started writing hdf5storage when I first switched from Matlab to Python. I had started a new project in Python as my first time working with Python and I needed to be save data in a way it could be read by others and Matlab's v7.3 format was more suitable than doing my own custom HDF5 schema. I also needed a way to read HDF5 files more generally due to my acquisition format. After a bit of time doing those two things separately, I mostly merged them and decided to make a much more general package that could read and write Python types losslessly (if sufficient metadata is enabled) while being compatible with Matlab v7.3; and that is how the hdf5storage package came to be.

Since I had just come from Matlab and was still using it a lot for another project, I wanted to read objects saved from Matlab as close as possible to how Matlab represented them whether it be when certain options are passed or by default. At the time back in 2013, that was the defaults for ``scipy.io.loadmat`` (https://docs.scipy.org/doc/scipy-0.13.0/reference/generated/scipy.io.loadmat.html) so it seemed reasonable to make that the default.

For storing Python objects and not reading them all distorted, I made a metadata format to specify enough information to read them back identically.
