### ISSUE TITLE
Error converting big matrices from matlab -v7.3 

### ISSUE THREAD

**Issue by fermat97** [frejanordsiek/hdf5storage#20]
Hi 
I tried to load matrices from matlab -v7.3 to python with hdf5storage.loadmat. This works with small matrices, however for the big matrices there is an error:
dtwhole = np.dtype(dt_whole)
ValueError: invalid shape in fixed-type tuple: dtype size in bytes must fit into a C int.

Do you have any idea whats wrong with the code?

this is my code in order to load matrices from matlab and also to save it back from python to matlab file:

def dict_keys_to_unicode(d): #change to unicode since all the keys in hdf5storage should be unicode
        out = dict()
        for k, v in d.items():
            out[k.decode()] = v
        return out  
class MatlabPythonFileConversionHDF5(object):
    def __init__(self,filepath_convfrom=None,filepath_convto=None,mat=None):
        self.filepath_convfrom = filepath_convfrom
        self.filepath_convto = filepath_convto
        self.mat = mat
    def Mat2PythonConvertor(self):
        self.output = hdf5storage.loadmat(self.filepath_convfrom)
        return self.output
    def Python2MatConvertor(self): 
        b = dict_keys_to_unicode(self.mat)  
        hdf5storage.savemat(self.filepath_convto, b,format='7.3')

**Comment by frejanordsiek** [comment]
I will attempt to do some tests to check it. I do have one guess, though. Are you running a 32-bit python environment? At least in 32-bit Python 2.x, internal memory pointers are going to be signed 32-bit integers (``numpy.int32``) meaning that you can't have any object larger than 2 GB. Trying to import data that large would cause such an error.

The error could be something else, though.

How big is the data and what python environment are you running (32/64-bit and 2.x/3.x)?

**Comment by fermat97** [comment]
It is a Linux CentOS Server 64-bit. I use a python version 2.7.5. The data can be loaded in Matlab without any problem (It is also possible to load matrices more than two times bigger than this in Matlab).The data is almost 5GB and the RAM is about 48GB

**Comment by frejanordsiek** [comment]
I know pointers in Python 3.x are 64-bit usually, but I not as sure on Python 2.x, even on 64-bit systems. I know GNU Octave at least had to be compiled differently to have them. The way to find out what the maximum size of a Numpy variable in Python 2.x is to run the following.

``` python
import numpy
numpy.iinfo(np.intp)
```

if it is something bigger than 2 GB (probably is on a 64-bit system), then I think I need to do some real digging for the bug.

**Comment by fermat97** [comment]
This is the output of the command:
Machine parameters for int64
---------------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------------

**Comment by frejanordsiek** [comment]
Thank you. There is not an issue with the python environment or numpy. There is a bug in the hdf5storage package that I need to track down.

So that I may try to reproduce it, can you tell me a bit about the data object you have in Matlab that you are trying to import. I can tell that it is a structure or structure array based on where you are getting an error. About how big is the structure array and what data types does it have inside it. Feel free to fudge the numbers and not give the field names using a description like

1000 x 2000 struct array with the following fields
  * double array that is usually around 30 x 100
  * cell array (about 10 x 1) of strings (about 100 characters)
  * structure with five scalar single fields

**Comment by fermat97** [comment]
Thank you.
Actually it is a Matlab matrix which is 8 000 000 x 80 double. I have also another Matrix which is 8 000 000 x 176 double.

**Comment by frejanordsiek** [comment]
Thanks for the info. I was able to reproduce the bug.

Unfortunately, this is actually a Numpy limitation that also uncovers a bug. I am going to open two issues with Numpy on this. There is a work around.

# Numpy Stuff (skip if you just want the work around)

Running ``hdf5storage.loadmat`` is basically doing a ``hdf5storage.read(path='/')`` which is reading the root of the file as if it was a structured ndarray. The two variables are read successfully and their dtypes obtained. The error happens when the dtype for the structured ndarray to hold them both together is constructed. I put in a print statement for ``dt_whole`` and got the following.

``[('a', dtype('float64'), (8000000, 80)), ('b', dtype('float64'), (8000000, 176))]``

Running that through ``np.dtype`` spits out the value error. The structured ndarray to hold this data is one element, but that one element has two huge fields. The size of the element is just larger than what can be handled. If I run it on a smaller one such as

``` python
c = np.dtype([('a', 'float64', (3300000, 80)), ('b', 'float64', (800000, 176))])
c.itemsize
````
I get the value ``-1056567296``, which makes is obviously wrong. If we calculate it by hand, the size should be ``3238400000``. If we try to store that as a 32-bit signed integer, which is ``- (2**31) + (3238400000 - 2**31)``, we get ``-1056567296``.

So Numpy is using 32-bit signed integers for dtypes. This can be seen in ``np.dtype([('a', 'int8', 2**31-1)])`` working but ``np.dtype([('a', 'int8', 2**31)])`` producing the same error. I don't exactly know how it didn't produce an error with the previous example. My guess is that it is not doing overflow checking.


# Work Around

If you read the two variables individually, this whole problem is circumvented. If their names in matlab were ``'a'`` and ``'b'``, then you would run

``` python
hdf5storage.loadmat('file.mat', variable_names=['a', 'b'])
```
which will read the specified names individually.


# Long Term Fix

In addition to hoping that Numpy fixes some of these issues in their next version, I am going to change the ``hdf5storage.loadmat`` command to, when not told which variables to load, just read ``'/'`` and extract the contents, it will instead get the list of all HDF5 Datasets and Groups under ``'/'`` and read them individually. This will also have the advantage of saving memory and processing time used in doing the extraction (memory copy).

**Comment by frejanordsiek** [comment]
The workaround has been added to the package. The commits are

master branch: [dff6d7d6](https://github.com/frejanordsiek/hdf5storage/commit/dff6d7d6e15c80c2139e209b73269a2df6aa977e)
0.1.x branch: [95f9727](https://github.com/frejanordsiek/hdf5storage/commit/95f9727788a5f013a1909b9dcad93cf00e1a9de5)

I will be putting the 0.1.7 release working around this issue up on PyPI tonight.

**Comment by frejanordsiek** [comment]
Version 0.1.7, with the work around, is now upploaded

https://pypi.python.org/pypi/hdf5storage

**Comment by frejanordsiek** [comment]
The issue I started on Numpy: [6235](https://github.com/numpy/numpy/issues/6235)

The gist is that the limit can either be ``2**31 - 1`` bytes (32 GB) or ``2**63-1`` depending on the system, even on 64-bit systems. This maximum size depends on things hardcoded into Numpy it seems. The overflow I found is something that might be fixed.

**Comment by seberg** [comment]
One small correction, the dtype is always limited to (signed) 32bits for the time being, since that is what a C-int is on all machines. Array sizes are limited to `ssize_t` which is 64bits on 64bit machines.

**Comment by frejanordsiek** [comment]
Oh, thank you for the correction and the information.

**Comment by fermat97** [comment]
Thank you. 
I just wanted to mention that I did not load the two matrices at the same time, the error appeared even with only 8 000 000 x 80 matrix alone. 
Now everything works fine

**Comment by frejanordsiek** [comment]
Glad it works now. Thank you for the help on this bug.
