### ISSUE TITLE
Add ability to read and write data selectively

### ISSUE THREAD

**Issue by erwindassen** [frejanordsiek/hdf5storage#29]
So far, if one wants to append data to a .mat file one had to read the whole file, mutate the dict containing data and write it again. In effect one is rewriting the whole file. With really big files this is undesirable. Instead one would like to read and write only selected keys (variables) from the file.

**Comment by frejanordsiek** [comment]
I dug into the code for ``savemat`` and it does indeed open the file, write the variable, and close the file for each single variable, which is a lot of overhead. While data can be added to HDF5 files without rewriting the whole thing, a lot of time is wasted reading its directory structure over and over again.

But it is slightly worse than that. In the ``write`` function, the file is opened at least twice. So, overally, for writing N variables, the file is opened 2N or 2N + 1 times (though that one extra time is a binary file open as opposed to an HDF5 file open and therefore less expensive).

You are right, this is undesirable and the penalty is larger for larger files.

It was originally written this way with the intent of eventually making it possible to pass multiple different variables to ``write`` to write at once, but I didn't get around to adding it. I was going to make it part of the 0.2 release, but it looks like it needs to be done quicker than that and be part of the 0.1.x releases since you presumably need it. I will try to get a fix for this this weekend and make a performancefix release (0.10). The hdf5storage package is already pretty slow at writing compared to reading, so this undoubtedly makes it even worse.

**Comment by frejanordsiek** [comment]
I added ``writes`` and ``reads`` functions to ``hdf5storage`` which can write and read multiple pieces of data at once without opening and closing the HDF5 file after each item. ``savemat`` and ``loadmat`` have been updated to use them, which should fix this performance issue. ``write`` and ``read`` have been turned into wrapper functions around them for the single data piece case.

The commits are

master: 3c93dea58fa9a54d5d6bb68291ddc7d82f70e268, 2b099d29f157b5793dccc8744e56a0e6c130a34c, 3938f8248b85d9662c78c004be572ac11a89ff6d, and d33bfe82c20a3373b6e37196d615c228be2839cd

0.1.x: 2bb70bb4ee3269d6da279d1db5990629fa1689d3, 4d997ed9481dcd9887369ae108191ddc3dcaa437, f020ad0bb7d287ede631a90126dee4b98e956efe, ce832b68f0b318196798bb794202edfde9420587

The 0.1.10 version has been made with these improvements and should be up on PyPi within an hour
