### ISSUE TITLE
RuntimeWarning: invalid value encountered in isnan

### ISSUE THREAD

**Issue by ghisvail** [frejanordsiek/hdf5storage#46]
Hi Freja,

The Debian CI is reporting quite a few RuntimeWarning raised whilst testing `hdf5storage` for the system Python 2 (2.7.12) and Python 3 (3.5.1). The log is available [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-hdf5storage/20160907_225148.autopkgtest.log.gz).

It does not make the CI testing fail but the generated noise may indicate that something is not working as intended, hence the report.

Cheers,

**Comment by frejanordsiek** [comment]
Those warnings have been with the package since day one. It has to do with how complex ndarrays are unpacked. Just doing ``realfield + 1j*imagfield`` works great except when one part is NaN or infinite and the other is not. For those entries, it sets them explicitly using complex(). The checks for those entries generate the warnings.

Recently, I did figure out a good way around the problem, one that is also faster. I was planning on putting it in to the 0.2 release, but I canput it into the 0.1.x series as well. I do need to do some testing first.

**Comment by frejanordsiek** [comment]
So I went through and found that what I thought was the issue was not. Some digging has shown that Numpy, with complex types, is not happy with all varieties of NaN in the real or imaginary parts.

Easiest way to set this up is to do the following.

``` python
import numpy as np
a = np.arange(0, 2**16, dtype='uint16')
b = a.view('float16')
c = np.complex64(b)
c.imag = b[::-1]
```

Doing ``np.isinf`` or ``np.isnan`` on ``b`` or on its real or imaginary parts leads to the runtime error. A particularly interesting place is ``c[511:513]`` which is ``array([ 3.04579735e-05+nanj,   3.05175781e-05+nanj], dtype=complex64)`` which are both NaN in the imaginary part. But doing ``np.isnan(c.imag[511])`` results in no warning while ``np.isnan(c.imag[511])`` results in the warning. If we look at their bytes representations, they are

element 511: ``b'\x00\x00\xc0\xff'``
element 512: ``b'\x00\xe0\xbf\xff'``

There are three options for the hdf5storage package. One is to just ignore the warning, another is to suppress the warnings, and the other is to try to convert all such NaN's to one Numpy likes for complex numbers. I think the middle one, suppressing the warnings, is probably best.

Either way, I am going to file an issue with the Numpy package, since this is a bigger problem.

**Comment by frejanordsiek** [comment]
Correct that, it is not just complex, but for float32 in general (and it would seem by extension, float64).

```
>>> import numpy
>>> a = numpy.ndarray(shape=(), dtype='float32', buffer=b'\x00\x00\xc0\xff')
>>> b = numpy.ndarray(shape=(), dtype='float32', buffer=b'\x00\xe0\xbf\xff')
```

Doing ``numpy.isnan(a)`` results in no warning while doing it on ``b`` results in a warning.

**Comment by frejanordsiek** [comment]
Yep, confirmed for float64. Also found that it does not exist for float16.

**Comment by frejanordsiek** [comment]
The warnings are now suppressed. The commits, by branch, are

master: fbfeb00
0.1.x: 2b5725f

Decided to improve the fragile, ugly, and slow complex decoding function in utilities as well (gets rid of more places for the warning to be raised as well)

master: 5602a1d
0.1.x: 4b38d26
