### ISSUE TITLE
Change default marshaller priority so that builtin marshallers have priority over user provided ones

### ISSUE THREAD

**Issue by frejanordsiek** [frejanordsiek/hdf5storage#62]
Previously, marshallers provided by a user to MarshallerCollection took priority over the builtin marshallers. Changing it to the other way around will make it more reliable to let external packages add their own persistent marshallers without any package being able to change the base behavior from which all other such packages might depend on.

**Comment by frejanordsiek** [comment]
Applied to the master branch in commit b142a14

**Comment by mincowski** [comment]
Hi, 
I love your package but this decision is something I can not understand.

Currently, I am trying to do exactly this: overwrite functionality of a built-in marshaller to be more useful for my application case (convert a numpy array of shape (1,1) to just the number).
This decision makes in very hard to actually do that since one can not just create a new marshaller for a certain type and add it to the collection. It will simply be ignored. So instead, one has to also create a custom marshaller class to get around this and duplicate a lot of code.

In my opinion, this defeats the purpose of the MarshallerCollection and makes the package way less easy to expand.
Also, I would expect that an user, loading an external package with additional marshallers, is doing that on purpose to modify the base behavior. Otherwise, why add a module?
Could you comment on why exactly you took that decision? Or am I missing a way to achieve the opposite? Because currently, this looks more like a bug than a feature to me.
Thanks!

**Comment by frejanordsiek** [comment]
You raise a very good point.

This decision does remove the ability to do what you want to do short of subclassing hdf5storage.MarshallerCollection and using it, which would be a pain.

I made the change because I am trying to add support for other packages to provide plugins that can provide additional marshallers and wanted a definitive loading priority to keep marshallers from different sources interfering with each other too much, and figured protecting the builtin ones would do that best.

However, after reading what you wrote, I realize that this is not the best decision. This ordering is legitimate, but so was the old one and the one you want to keep.

So, I think the best solution is to make the order configurable, to allow the user to decide what the priority order should be for user provided marshallers, builtin marshallers, and plugin marshallers. I will implement this.

Also, I probably should make it possible to get all the available marshallers and make it possible for the user to set the loading order explicitly (allow interleaving of priorities).

As for the feature you are trying to do with overloading the builtin marshaller, that is actually a good candidate for a feature that would be controlled by an option to add to the builtin marshaller. You probably aren't the only one to want such a feature. It seems like a good idea to add.

**Comment by frejanordsiek** [comment]
Made it so that the priority can be selected in the master branch in commit 4df9399 . Tests added in commit 4431f26 , with CI testing with the example plugin package enabled with commit 8a0bae5 .

**Comment by mincowski** [comment]
Wow, that was fast. Thanks a lot! I'll go ahead and update my code right away.
Your choices here seem to make sense. I can understand that you want to prevent packages from interfering with each other and giving the user the choice to increase the priority of their own marshallers solves my problem.

**Comment by frejanordsiek** [comment]
I was almost done with the initial plugin code and had been thinking about the priority algorithm quite a bit, so it was just a matter of finishing and committing it and then adding the option (that and 7 hours of train ride to use yesterday).

Unfortunately, even this limited form of control still leaves a lot of potential conflicts. I am still trying to think of the best way to make it so users can include and exclude subsets of marshallers and fine tune the priorities. Going to try to get something reasonable before the first non 0.1.x release which will still take quite a while to do (plan on getting enough of the loose ends done for it to be the first beta release instead of another alpha release so then can do a stable 1.0 release at some point within the next year).
