### ISSUE TITLE
Read matlab struct members into a python dict instead of numpy structured array

### ISSUE THREAD

**Issue by bear24rw** [frejanordsiek/hdf5storage#64]
I ran into this bug in numpy when reading in a .mat that has a struct containing huge matrices. (the dtwhole dtype was > 2GB)

https://github.com/numpy/numpy/issues/6235

I was able to work around this bug by returning the python dict `struct_data` early instead of trying to convert it to a numpy structure:

```
diff --git a/hdf5storage/Marshallers.py b/hdf5storage/Marshallers.py
index a37fbbf..74a363c 100644
--- a/hdf5storage/Marshallers.py
+++ b/hdf5storage/Marshallers.py
@@ -1079,6 +1079,9 @@ class NumpyScalarArrayMarshaller(TypeMarshaller):
                 except:
                     pass

+            if matlab_class == 'struct':
+                return struct_data
+
             # If it isn't multi element, we need to pack all the values
             # in struct_array inside of numpy.object_'s so that the code
             # after this that depends on this will work.
```

Is there any disadvantage to doing this? Could this be made the default or an option flag?

**Comment by frejanordsiek** [comment]
Only issue is that for struct arrays, it won't be possible to index by number first and then field second (one has to do it the other way around). However, even then, making it say a list of dict might be a good idea.

As for whether it should be an option, most definitely yes it should be. Also, now that I think about it, I think it would be useful to have the code actually check to see if the dtype's size would overflow and then return as a dict or list of dict in the case it does so then the package will still work even with the default options.

**Comment by batterseapower** [comment]
I think I'm being bitten by this bug. It took a while to figure out what was going on because hdf5storage just swallows the relevant exception (https://github.com/frejanordsiek/hdf5storage/blob/master/hdf5storage/Marshallers.py#L1090) and the problem manifests as the structure being missing from the result. At the very least I think it should log, but personally I don't think that the library should hide the exception at all -- it's surprising that variables can be silently dropped if you hit this bug, run out of memory etc.

**Comment by frejanordsiek** [comment]
The PR was merged in, so now there is at least a manual solution. Hope to eventually write an automatic solution as well.
